'use client';

import { useState, useMemo } from 'react';
import { UpdateItem, Priority } from '@/lib/types';
import { copyToClipboard } from '@/lib/docx-generator';
import { 
  Share2, 
  Copy, 
  Check, 
  Calendar,
  ChevronDown,
  ChevronUp,
  AlertCircle,
  Zap,
  MessageSquare,
} from 'lucide-react';

interface ShareUpdateProps {
  updates: UpdateItem[];
}

type ShareFormat = 'slack' | 'email' | 'brief';

const FORMAT_OPTIONS: { id: ShareFormat; label: string; description: string }[] = [
  { id: 'slack', label: 'Slack Message', description: 'Formatted for Slack with emoji' },
  { id: 'email', label: 'Email Update', description: 'Professional email format' },
  { id: 'brief', label: 'Brief Summary', description: 'Quick bullet points only' },
];

function formatTime(minutes: number | null): string {
  if (minutes === null) return '';
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  const period = hours >= 12 ? 'PM' : 'AM';
  const displayHours = hours > 12 ? hours - 12 : hours === 0 ? 12 : hours;
  return `${displayHours}:${mins.toString().padStart(2, '0')} ${period}`;
}

function generateSlackMessage(updates: UpdateItem[], date: string): string {
  const relevantUpdates = updates.filter(u => u.category !== 'Noise');
  const highPriority = relevantUpdates.filter(u => u.priority === 'High');
  const protocols = relevantUpdates.filter(u => u.category === 'Protocol' && u.priority !== 'High');
  const incidents = relevantUpdates.filter(u => u.category === 'Incident' && u.priority !== 'High');
  const announcements = relevantUpdates.filter(u => u.category === 'Announcement' && u.priority !== 'High');
  const reminders = relevantUpdates.filter(u => u.category === 'Reminder');
  const fyi = relevantUpdates.filter(u => u.category === 'FYI');

  let message = `📋 *IC Team Updates* — ${date}\n\n`;

  if (highPriority.length > 0) {
    message += `🚨 *HIGH PRIORITY*\n`;
    highPriority.forEach(item => {
      message += `• *${item.title}*`;
      if (item.owner) message += ` (${item.owner})`;
      message += `\n  ${item.summary}\n`;
      if (item.links.length > 0) {
        message += `  🔗 ${item.links[0]}\n`;
      }
    });
    message += '\n';
  }

  if (protocols.length > 0) {
    message += `📝 *Protocol Updates*\n`;
    protocols.forEach(item => {
      message += `• ${item.title}`;
      if (item.owner) message += ` — _${item.owner}_`;
      message += '\n';
    });
    message += '\n';
  }

  if (incidents.length > 0) {
    message += `⚠️ *Incidents/Issues*\n`;
    incidents.forEach(item => {
      message += `• ${item.title}`;
      if (item.owner) message += ` — _${item.owner}_`;
      message += '\n';
    });
    message += '\n';
  }

  if (announcements.length > 0) {
    message += `📢 *Announcements*\n`;
    announcements.forEach(item => {
      message += `• ${item.title}`;
      if (item.owner) message += ` — _${item.owner}_`;
      message += '\n';
    });
    message += '\n';
  }

  if (reminders.length > 0) {
    message += `⏰ *Reminders*\n`;
    reminders.forEach(item => {
      message += `• ${item.title}\n`;
    });
    message += '\n';
  }

  if (fyi.length > 0) {
    message += `ℹ️ *FYI*\n`;
    fyi.forEach(item => {
      message += `• ${item.title}\n`;
    });
    message += '\n';
  }

  message += `—\n_Generated by IC Updates_`;

  return message;
}

function generateEmailMessage(updates: UpdateItem[], date: string): string {
  const relevantUpdates = updates.filter(u => u.category !== 'Noise');
  const highPriority = relevantUpdates.filter(u => u.priority === 'High');
  const others = relevantUpdates.filter(u => u.priority !== 'High');

  let message = `IC Team Updates — ${date}\n`;
  message += `${'='.repeat(40)}\n\n`;

  if (highPriority.length > 0) {
    message += `** HIGH PRIORITY **\n\n`;
    highPriority.forEach(item => {
      message += `→ ${item.title}\n`;
      message += `  ${item.summary}\n`;
      if (item.owner) message += `  Owner: ${item.owner}\n`;
      if (item.links.length > 0) message += `  Link: ${item.links[0]}\n`;
      message += '\n';
    });
  }

  if (others.length > 0) {
    message += `OTHER UPDATES\n\n`;
    others.forEach(item => {
      message += `• [${item.category}] ${item.title}`;
      if (item.owner) message += ` (${item.owner})`;
      message += '\n';
    });
    message += '\n';
  }

  message += `—\nGenerated by IC Updates`;

  return message;
}

function generateBriefMessage(updates: UpdateItem[], date: string): string {
  const relevantUpdates = updates.filter(u => u.category !== 'Noise');
  
  let message = `IC Updates — ${date}\n\n`;
  
  relevantUpdates.forEach(item => {
    const priorityMarker = item.priority === 'High' ? '🔴 ' : '';
    message += `${priorityMarker}• ${item.title}\n`;
  });

  return message;
}

export default function ShareUpdate({ updates }: ShareUpdateProps) {
  const [format, setFormat] = useState<ShareFormat>('slack');
  const [date, setDate] = useState<string>(new Date().toLocaleDateString());
  const [copied, setCopied] = useState(false);
  const [showPreview, setShowPreview] = useState(true);
  const [includeCategories, setIncludeCategories] = useState({
    high: true,
    protocols: true,
    incidents: true,
    announcements: true,
    reminders: true,
    fyi: false,
  });

  const relevantUpdates = useMemo(() => {
    return updates.filter(u => {
      if (u.category === 'Noise') return false;
      if (u.priority === 'High' && !includeCategories.high) return false;
      if (u.category === 'Protocol' && u.priority !== 'High' && !includeCategories.protocols) return false;
      if (u.category === 'Incident' && u.priority !== 'High' && !includeCategories.incidents) return false;
      if (u.category === 'Announcement' && u.priority !== 'High' && !includeCategories.announcements) return false;
      if (u.category === 'Reminder' && !includeCategories.reminders) return false;
      if (u.category === 'FYI' && !includeCategories.fyi) return false;
      return true;
    });
  }, [updates, includeCategories]);

  const generatedMessage = useMemo(() => {
    switch (format) {
      case 'slack':
        return generateSlackMessage(relevantUpdates, date);
      case 'email':
        return generateEmailMessage(relevantUpdates, date);
      case 'brief':
        return generateBriefMessage(relevantUpdates, date);
    }
  }, [relevantUpdates, date, format]);

  const handleCopy = async () => {
    const success = await copyToClipboard(generatedMessage);
    if (success) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  if (updates.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-64 text-surface-500">
        <Share2 className="w-12 h-12 mb-3 text-surface-300" />
        <p className="text-lg font-medium">No updates to share</p>
        <p className="text-sm">Paste Slack messages and click Parse first</p>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <div className="p-2 bg-primary-100 rounded-lg">
          <Share2 className="w-5 h-5 text-primary-600" />
        </div>
        <div>
          <h2 className="font-semibold text-surface-900">Share Update</h2>
          <p className="text-sm text-surface-500">Generate a single message to share with everyone</p>
        </div>
      </div>

      {/* Configuration */}
      <div className="p-6 bg-white border border-surface-200 rounded-lg space-y-4">
        <h3 className="font-medium text-surface-900">Message Settings</h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Format Selection */}
          <div>
            <label className="block text-sm font-medium text-surface-700 mb-2">Format</label>
            <div className="space-y-2">
              {FORMAT_OPTIONS.map((opt) => (
                <label
                  key={opt.id}
                  className={`flex items-start gap-3 p-3 rounded-lg border cursor-pointer transition-colors
                    ${format === opt.id 
                      ? 'border-primary-500 bg-primary-50' 
                      : 'border-surface-200 hover:bg-surface-50'}`}
                >
                  <input
                    type="radio"
                    name="format"
                    value={opt.id}
                    checked={format === opt.id}
                    onChange={(e) => setFormat(e.target.value as ShareFormat)}
                    className="mt-0.5"
                  />
                  <div>
                    <div className="font-medium text-surface-900">{opt.label}</div>
                    <div className="text-xs text-surface-500">{opt.description}</div>
                  </div>
                </label>
              ))}
            </div>
          </div>

          {/* Date and Include Options */}
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-surface-700 mb-2">
                <Calendar className="w-4 h-4 inline mr-1" />
                Date Label
              </label>
              <input
                type="text"
                value={date}
                onChange={(e) => setDate(e.target.value)}
                placeholder="e.g., Monday Jan 12"
                className="w-full px-3 py-2 border border-surface-200 rounded-lg
                         focus:outline-none focus:ring-2 focus:ring-primary-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-surface-700 mb-2">Include Sections</label>
              <div className="space-y-2">
                {[
                  { key: 'high', label: 'High Priority', color: 'text-red-600' },
                  { key: 'protocols', label: 'Protocols', color: 'text-purple-600' },
                  { key: 'incidents', label: 'Incidents', color: 'text-orange-600' },
                  { key: 'announcements', label: 'Announcements', color: 'text-blue-600' },
                  { key: 'reminders', label: 'Reminders', color: 'text-amber-600' },
                  { key: 'fyi', label: 'FYI', color: 'text-green-600' },
                ].map((item) => (
                  <label key={item.key} className="flex items-center gap-2 text-sm">
                    <input
                      type="checkbox"
                      checked={includeCategories[item.key as keyof typeof includeCategories]}
                      onChange={(e) => setIncludeCategories(prev => ({
                        ...prev,
                        [item.key]: e.target.checked
                      }))}
                      className="w-4 h-4 rounded border-surface-300 text-primary-600"
                    />
                    <span className={item.color}>{item.label}</span>
                  </label>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Stats */}
        <div className="pt-4 border-t border-surface-100 flex items-center gap-4 text-sm text-surface-600">
          <span className="flex items-center gap-1">
            <MessageSquare className="w-4 h-4" />
            {relevantUpdates.length} updates included
          </span>
          <span className="flex items-center gap-1">
            <Zap className="w-4 h-4 text-red-500" />
            {relevantUpdates.filter(u => u.priority === 'High').length} high priority
          </span>
        </div>
      </div>

      {/* Copy Button - Prominent */}
      <div className="flex gap-3">
        <button
          onClick={handleCopy}
          disabled={relevantUpdates.length === 0}
          className="flex-1 flex items-center justify-center gap-2 py-4 px-6 
                   bg-primary-600 hover:bg-primary-700 disabled:bg-surface-300
                   text-white font-semibold rounded-lg transition-colors text-lg"
        >
          {copied ? (
            <>
              <Check className="w-6 h-6" />
              Copied to Clipboard!
            </>
          ) : (
            <>
              <Copy className="w-6 h-6" />
              Copy Message to Share
            </>
          )}
        </button>
      </div>

      {/* Preview */}
      <div className="p-6 bg-white border border-surface-200 rounded-lg">
        <button
          onClick={() => setShowPreview(!showPreview)}
          className="flex items-center justify-between w-full text-left"
        >
          <h3 className="font-medium text-surface-900">Message Preview</h3>
          {showPreview ? (
            <ChevronUp className="w-5 h-5 text-surface-400" />
          ) : (
            <ChevronDown className="w-5 h-5 text-surface-400" />
          )}
        </button>

        {showPreview && (
          <div className="mt-4">
            {relevantUpdates.length === 0 ? (
              <div className="flex items-center gap-2 text-surface-500 p-4 bg-surface-50 rounded">
                <AlertCircle className="w-4 h-4" />
                No updates to include. Adjust your include settings above.
              </div>
            ) : (
              <pre className="p-4 bg-surface-50 rounded-lg border border-surface-200 
                            text-sm font-mono text-surface-700 whitespace-pre-wrap 
                            overflow-x-auto max-h-96">
                {generatedMessage}
              </pre>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

